export const walletTypeValues = [
  "cash",
  "bank",
  "savings",
  "credit_card",
  "crypto",
  "investment",
  "custom",
] as const;

export const transactionTypeValues = ["income", "expense", "transfer"] as const;
export const billingCycleValues = ["weekly", "monthly", "yearly"] as const;
export const subscriptionStatusValues = ["active", "paused", "cancelled"] as const;
export const goalStatusValues = ["on_track", "ahead", "behind", "completed", "paused"] as const;
export const priorityValues = ["low", "medium", "high"] as const;
export const riskLevelValues = ["low", "medium", "high"] as const;
export const insightSeverityValues = ["info", "success", "warning", "critical"] as const;
export const rubyRoleValues = ["user", "assistant", "system"] as const;
export const planTypeValues = ["free", "pro"] as const;
export const categoryTypeValues = ["income", "expense", "transfer"] as const;

export type TableColumn = {
  name: string;
  type: string;
  nullable?: boolean;
  default?: string;
  references?: string;
  notes?: string;
};

export type TableDefinition = {
  name: string;
  description: string;
  primaryKey: string;
  columns: TableColumn[];
  indexes?: string[];
};

export const financeSchemaFoundation: TableDefinition[] = [
  {
    name: "profiles",
    description: "User profile and onboarding-level finance preferences.",
    primaryKey: "id",
    columns: [
      { name: "id", type: "uuid", references: "auth.users(id)" },
      { name: "full_name", type: "text", nullable: true },
      { name: "avatar_url", type: "text", nullable: true },
      { name: "preferred_currency", type: "text", default: "'USD'" },
      { name: "country", type: "text", nullable: true },
      { name: "monthly_income", type: "numeric", default: "0" },
      { name: "savings_target", type: "numeric", default: "0" },
      { name: "ruby_ai_focus", type: "text", nullable: true },
      { name: "onboarding_completed", type: "boolean", default: "false" },
      { name: "created_at", type: "timestamptz", default: "now()" },
      { name: "updated_at", type: "timestamptz", default: "now()" },
    ],
  },
  {
    name: "wallets",
    description: "User-owned account/wallet balances and source metadata.",
    primaryKey: "id",
    columns: [
      { name: "id", type: "uuid" },
      { name: "user_id", type: "uuid", references: "profiles(id)" },
      { name: "name", type: "text" },
      { name: "type", type: "text", notes: walletTypeValues.join(" | ") },
      { name: "balance", type: "numeric" },
      { name: "currency", type: "text" },
      { name: "provider", type: "text", nullable: true },
      { name: "is_manual", type: "boolean", default: "true" },
      { name: "last_synced_at", type: "timestamptz", nullable: true },
      { name: "created_at", type: "timestamptz", default: "now()" },
      { name: "updated_at", type: "timestamptz", default: "now()" },
    ],
    indexes: ["user_id", "type", "created_at"],
  },
  {
    name: "categories",
    description: "Default and user-defined transaction categories.",
    primaryKey: "id",
    columns: [
      { name: "id", type: "uuid" },
      { name: "user_id", type: "uuid", references: "profiles(id)", nullable: true },
      { name: "name", type: "text" },
      { name: "type", type: "text", notes: categoryTypeValues.join(" | ") },
      { name: "icon", type: "text", nullable: true },
      { name: "color", type: "text", nullable: true },
      { name: "is_default", type: "boolean", default: "false" },
      { name: "created_at", type: "timestamptz", default: "now()" },
      { name: "updated_at", type: "timestamptz", default: "now()" },
    ],
    indexes: ["user_id", "type", "is_default"],
  },
  {
    name: "transactions",
    description: "Ledger of all user financial movements.",
    primaryKey: "id",
    columns: [
      { name: "id", type: "uuid" },
      { name: "user_id", type: "uuid", references: "profiles(id)" },
      { name: "wallet_id", type: "uuid", references: "wallets(id)" },
      { name: "merchant", type: "text", nullable: true },
      { name: "description", type: "text" },
      { name: "amount", type: "numeric" },
      { name: "currency", type: "text" },
      { name: "type", type: "text", notes: transactionTypeValues.join(" | ") },
      { name: "category_id", type: "uuid", references: "categories(id)", nullable: true },
      { name: "category_name", type: "text" },
      { name: "date", type: "date" },
      { name: "tags", type: "text[]", default: "'{}'" },
      { name: "is_recurring", type: "boolean", default: "false" },
      { name: "ai_flags", type: "jsonb", default: "'[]'::jsonb" },
      { name: "confidence_score", type: "numeric", nullable: true },
      { name: "created_at", type: "timestamptz", default: "now()" },
      { name: "updated_at", type: "timestamptz", default: "now()" },
    ],
    indexes: ["user_id", "wallet_id", "date", "type"],
  },
  {
    name: "subscriptions",
    description: "Recurring subscription contracts and optimization insights.",
    primaryKey: "id",
    columns: [
      { name: "id", type: "uuid" },
      { name: "user_id", type: "uuid", references: "profiles(id)" },
      { name: "wallet_id", type: "uuid", references: "wallets(id)", nullable: true },
      { name: "name", type: "text" },
      { name: "amount", type: "numeric" },
      { name: "currency", type: "text" },
      { name: "billing_cycle", type: "text", notes: billingCycleValues.join(" | ") },
      { name: "next_billing_date", type: "date" },
      { name: "category_id", type: "uuid", references: "categories(id)", nullable: true },
      { name: "category_name", type: "text" },
      { name: "status", type: "text", notes: subscriptionStatusValues.join(" | ") },
      { name: "yearly_cost", type: "numeric" },
      { name: "optimization_status", type: "text", nullable: true },
      { name: "ai_recommendation", type: "text", nullable: true },
      { name: "usage_status", type: "text", nullable: true },
      { name: "created_at", type: "timestamptz", default: "now()" },
      { name: "updated_at", type: "timestamptz", default: "now()" },
    ],
    indexes: ["user_id", "status", "next_billing_date"],
  },
  {
    name: "goals",
    description: "Savings and planning goals with AI progress assistance.",
    primaryKey: "id",
    columns: [
      { name: "id", type: "uuid" },
      { name: "user_id", type: "uuid", references: "profiles(id)" },
      { name: "title", type: "text" },
      { name: "target_amount", type: "numeric" },
      { name: "current_amount", type: "numeric" },
      { name: "currency", type: "text" },
      { name: "deadline", type: "date", nullable: true },
      { name: "status", type: "text", notes: goalStatusValues.join(" | ") },
      { name: "monthly_target", type: "numeric" },
      { name: "predicted_completion_date", type: "date", nullable: true },
      { name: "priority", type: "text", notes: priorityValues.join(" | ") },
      { name: "ai_recommendation", type: "text", nullable: true },
      { name: "created_at", type: "timestamptz", default: "now()" },
      { name: "updated_at", type: "timestamptz", default: "now()" },
    ],
    indexes: ["user_id", "status", "priority"],
  },
  {
    name: "budgets",
    description: "Monthly budget snapshots and safe-to-spend projection base.",
    primaryKey: "id",
    columns: [
      { name: "id", type: "uuid" },
      { name: "user_id", type: "uuid", references: "profiles(id)" },
      { name: "month", type: "text" },
      { name: "total_income", type: "numeric" },
      { name: "planned_spending", type: "numeric" },
      { name: "savings_target", type: "numeric" },
      { name: "safe_to_spend_daily", type: "numeric" },
      { name: "status", type: "text" },
      { name: "created_at", type: "timestamptz", default: "now()" },
      { name: "updated_at", type: "timestamptz", default: "now()" },
    ],
    indexes: ["user_id", "month"],
  },
  {
    name: "budget_categories",
    description: "Per-budget category planning and risk monitoring lines.",
    primaryKey: "id",
    columns: [
      { name: "id", type: "uuid" },
      { name: "budget_id", type: "uuid", references: "budgets(id)" },
      { name: "category_id", type: "uuid", references: "categories(id)", nullable: true },
      { name: "category_name", type: "text" },
      { name: "planned_amount", type: "numeric" },
      { name: "spent_amount", type: "numeric" },
      { name: "remaining_amount", type: "numeric" },
      { name: "risk_level", type: "text", notes: riskLevelValues.join(" | ") },
      { name: "ai_comment", type: "text", nullable: true },
      { name: "created_at", type: "timestamptz", default: "now()" },
      { name: "updated_at", type: "timestamptz", default: "now()" },
    ],
    indexes: ["budget_id", "risk_level"],
  },
  {
    name: "ai_insights",
    description: "Generated AI insights, recommendations and resolution state.",
    primaryKey: "id",
    columns: [
      { name: "id", type: "uuid" },
      { name: "user_id", type: "uuid", references: "profiles(id)" },
      { name: "type", type: "text" },
      { name: "title", type: "text" },
      { name: "description", type: "text" },
      { name: "severity", type: "text", notes: insightSeverityValues.join(" | ") },
      { name: "confidence", type: "numeric" },
      { name: "financial_impact", type: "numeric", nullable: true },
      { name: "suggested_action", type: "text", nullable: true },
      { name: "related_entity_type", type: "text", nullable: true },
      { name: "related_entity_id", type: "uuid", nullable: true },
      { name: "is_resolved", type: "boolean", default: "false" },
      { name: "created_at", type: "timestamptz", default: "now()" },
      { name: "resolved_at", type: "timestamptz", nullable: true },
    ],
    indexes: ["user_id", "severity", "is_resolved"],
  },
  {
    name: "monthly_reports",
    description: "Computed monthly reporting snapshots and AI summary output.",
    primaryKey: "id",
    columns: [
      { name: "id", type: "uuid" },
      { name: "user_id", type: "uuid", references: "profiles(id)" },
      { name: "month", type: "text" },
      { name: "total_income", type: "numeric" },
      { name: "total_expenses", type: "numeric" },
      { name: "net_savings", type: "numeric" },
      { name: "savings_rate", type: "numeric" },
      { name: "health_score", type: "numeric" },
      { name: "previous_health_score", type: "numeric", nullable: true },
      { name: "top_categories", type: "jsonb", default: "'[]'::jsonb" },
      { name: "subscription_impact", type: "jsonb", default: "'{}'::jsonb" },
      { name: "goal_progress", type: "jsonb", default: "'[]'::jsonb" },
      { name: "ai_summary", type: "text" },
      { name: "recommended_actions", type: "jsonb", default: "'[]'::jsonb" },
      { name: "created_at", type: "timestamptz", default: "now()" },
      { name: "updated_at", type: "timestamptz", default: "now()" },
    ],
    indexes: ["user_id", "month"],
  },
  {
    name: "ruby_ai_conversations",
    description: "Conversation container for Ruby AI assistant chats.",
    primaryKey: "id",
    columns: [
      { name: "id", type: "uuid" },
      { name: "user_id", type: "uuid", references: "profiles(id)" },
      { name: "title", type: "text" },
      { name: "mode", type: "text", nullable: true },
      { name: "created_at", type: "timestamptz", default: "now()" },
      { name: "updated_at", type: "timestamptz", default: "now()" },
    ],
    indexes: ["user_id", "created_at"],
  },
  {
    name: "ruby_ai_messages",
    description: "Message stream for each Ruby AI conversation.",
    primaryKey: "id",
    columns: [
      { name: "id", type: "uuid" },
      { name: "conversation_id", type: "uuid", references: "ruby_ai_conversations(id)" },
      { name: "user_id", type: "uuid", references: "profiles(id)" },
      { name: "role", type: "text", notes: rubyRoleValues.join(" | ") },
      { name: "content", type: "text" },
      { name: "metadata", type: "jsonb", nullable: true, default: "'{}'::jsonb" },
      { name: "created_at", type: "timestamptz", default: "now()" },
    ],
    indexes: ["conversation_id", "created_at"],
  },
  {
    name: "app_settings",
    description: "User-level app and personalization settings.",
    primaryKey: "id",
    columns: [
      { name: "id", type: "uuid" },
      { name: "user_id", type: "uuid", references: "profiles(id)" },
      { name: "theme", type: "text", default: "'dark'" },
      { name: "accent_color", type: "text", default: "'red'" },
      { name: "compact_mode", type: "boolean", default: "false" },
      { name: "animations_enabled", type: "boolean", default: "true" },
      { name: "insight_frequency", type: "text", default: "'weekly'" },
      { name: "risk_sensitivity", type: "text", default: "'medium'" },
      { name: "student_mode", type: "boolean", default: "false" },
      { name: "created_at", type: "timestamptz", default: "now()" },
      { name: "updated_at", type: "timestamptz", default: "now()" },
    ],
    indexes: ["user_id"],
  },
  {
    name: "user_plans",
    description: "Plan status and billing lifecycle metadata for monetization.",
    primaryKey: "id",
    columns: [
      { name: "id", type: "uuid" },
      { name: "user_id", type: "uuid", references: "profiles(id)" },
      { name: "plan_type", type: "text", default: "'free'", notes: planTypeValues.join(" | ") },
      { name: "billing_cycle", type: "text", nullable: true, notes: billingCycleValues.join(" | ") },
      { name: "status", type: "text", default: "'active'" },
      { name: "started_at", type: "timestamptz", default: "now()" },
      { name: "expires_at", type: "timestamptz", nullable: true },
      { name: "created_at", type: "timestamptz", default: "now()" },
      { name: "updated_at", type: "timestamptz", default: "now()" },
    ],
    indexes: ["user_id", "plan_type", "status"],
  },
];
