-- Create feedback table for user support tickets
CREATE TABLE public.feedbacks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  type text check (type in ('bug', 'suggestion', 'report', 'general')) not null default 'general',
  subject text not null,
  message text not null,
  status text check (status in ('pending', 'in_progress', 'resolved', 'closed')) not null default 'pending',
  admin_response text,
  rating integer check (rating >= 1 and rating <= 5),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE public.feedbacks ENABLE ROW LEVEL SECURITY;

-- Users can create their own feedback
CREATE POLICY "Users can create own feedback"
ON public.feedbacks FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Users can view their own feedback
CREATE POLICY "Users can view own feedback"
ON public.feedbacks FOR SELECT
USING (auth.uid() = user_id);

-- Users can update rating on their own feedback
CREATE POLICY "Users can update own feedback rating"
ON public.feedbacks FOR UPDATE
USING (auth.uid() = user_id);

-- Admins can view all feedback
CREATE POLICY "Admins can view all feedback"
ON public.feedbacks FOR SELECT
USING (has_role(auth.uid(), 'admin'));

-- Admins can update all feedback (for responses)
CREATE POLICY "Admins can update all feedback"
ON public.feedbacks FOR UPDATE
USING (has_role(auth.uid(), 'admin'));

-- Create trigger for updating updated_at
CREATE OR REPLACE FUNCTION public.update_feedback_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

CREATE TRIGGER update_feedbacks_updated_at
BEFORE UPDATE ON public.feedbacks
FOR EACH ROW
EXECUTE FUNCTION public.update_feedback_updated_at();